### ISSUE TITLE
Run with swagger ui error

### ISSUE THREAD

**Issue by pobearm** [zc2638/swag#20]
1. My demo code  from readme of project . code version:  v1.4.1. 
```golang
apiDoc := swag.New(
  option.Title("demo API Doc"),
)
 ...

// Register Swagger JSON route
r.GET("/swagger/json",
  gin.WrapH(apiDoc.Handler()),
)

// Register Swagger UI route
// To take effect, the swagger json route must be registered
r.GET("/swagger/ui/*any",
gin.WrapH(
	swag.UIHandler("/swagger/ui", "/swagger/json", true),
),
)
```

2. Visti our web. 
    http://localhost:8080/swagger/json     It is response the json of doc correctly.
    http://localhost:8080/swagger/ui/      it return error:  index.html read exception.
    http://localhost:8080/swagger/ui/index.html       the same error. 

3.  The embbed file pkg (assert) has some error?

**Comment by pobearm** [comment]
`package main

import (
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/zc2638/swag"

	"github.com/zc2638/swag/option"
)

func main() {

	router := gin.New()

	regApiRouter(router)

	log.Fatal(http.ListenAndServe(":8080", router))
}

func regApiRouter(r *gin.Engine) {
	apiDoc := swag.New(
		option.Title("demo API Doc"),
	)

	// api.InitRouter(apiDoc, r)

	// Register Swagger JSON route
	r.GET("/swagger/json",
		gin.WrapH(apiDoc.Handler()),
	)

	// Register Swagger UI route
	// To take effect, the swagger json route must be registered
	r.GET("/swagger/ui/*any",
		gin.WrapH(
			swag.UIHandler("/swagger/ui", "/swagger/json", true),
		),
	)

}`

**Comment by pobearm** [comment]
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOENV=C:\Users\xxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\gopath
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Programs\Go19
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Programs\Go19\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\go_code\ddd_demo\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\matebook\AppData\Local\Temp\go-build1670206615=/tmp/go-build -gno-record-gcc-switches

**Comment by pobearm** [comment]
I debug the code .
In file api.go , line : 406. 
```
fullName := filepath.Join(asserts.DistDir, "index.html")
fileData, err := asserts.Dist.ReadFile(fullName)
```
The fullName value is: "dist\\index.html" , the cause err:  "file does not exist".

**Comment by zc2638** [comment]
Thanks, I will test windows later.
I would really appreciate it if you could help out.

**Comment by zc2638** [comment]
https://github.com/golang/go/issues/44305
Looks like `filepath.Join` problem, we should use `path.Join`.
/assign @TianTianBigWang

**Comment by TianTianBigWang** [comment]
It looks so right, I will fix it

**Comment by zc2638** [comment]
Now, you can use v1.4.2 on windows.
@pobearm
