### ISSUE TITLE
是否可以移除对github.com/99nil/gopkg包的依赖

### ISSUE THREAD

**Issue by pobearm** [zc2638/swag#24]
Big wang:
    我们可以不依赖这个github.com/99nil/gopkg包么? 
    你可以用go mod graph看一下这个包的依赖关系, 简直是恐怖.
    他里面又依赖github.com/spf13/viper这个脑残包, 什么玩意都加进来.

   可以装个图形化的工具看依赖关系, 比如:
         go install github.com/PaulXu-cn/go-mod-graph-chart/gmchart
         go mod graph | gmchart
   这样可以看到图片. 
   
   哈哈.

**Comment by pobearm** [comment]
兄弟, still alive?

**Comment by zc2638** [comment]
在这周会更新依赖，以减少外部依赖。
如果你有时间，也可以提交PR
